sslEnable: true

server:
  port: 8080

spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt
  application:
    name: LocationDataMaster
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
  kafka:
    listener:
      concurrency: 1
      ack-mode: MANUAL_IMMEDIATE
    auto:
      create:
        topics:
          enable: true
    #bootstrap-servers: localhost:29092
    bootstrap-servers: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
    username: YGZWSL4IE7B7EUKG
    password: yXBPPcK4ZIHRII0ybeGpFaXsLDJn8HBFHLnvgkJC8SApSQ46mhyR/NnOmbzVu0WF
    producer:
      producerLinger: "1"
      producerTimeout: "30000"
      producerAcksConfig: "all"
      topic: apmm.locationref.topic.internal.any.v1


azure:
  blob:
    #connectionString: DefaultEndpointsProtocol=https;AccountName=locationmaster;AccountKey=HCuKWNJWk51o+KiXK88ynl8KyNqTImPXxTi7YYGsSFf8Y83vfHw/DUoWZv6vcmj9jAOLTcycj/1E+ASt5Izenw==;EndpointSuffix=core.windows.net
    connectionString:  DefaultEndpointsProtocol=https;AccountName=locationpocstorage;AccountKey=krJ9WTVgPbsSBhIUvwI4BkxiWmiB4zdNYpTXZ/vNO0ZVa2rAExlo9sGvzpK6KDDiAZdejhgkvUD2+AStIDvj/g==;EndpointSuffix=core.windows.net
    containerName: locationpoccontainer
    blobName: locationmaster


producer-kafka-config:
  bootstrap-servers: pkc-4r087.us-west2.gcp.confluent.cloud:9092
  username: KNGLYLYVX4UYIZN5
  password: 0vYFQj2zSwVLVLgemUcWVAHy/i2FR0YzMXC757dV/kRE+W7idYFMCfId6rHkE6uK
  clientId: locationData
  topic: apmm.locationref.topic.internal.any.v1

logging.level.io.confluent.kafka: DEBUG




