#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: producer-service
#  labels:
#    app: producer-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: producer-service
#  template:
#    metadata:
#      labels:
#        app: producer-service
#    spec:
#      containers:
#        - name: nginx
#          image: locationpocregistry.azurecr.io/producer-service:v1
#          ports:
#            - containerPort: 8080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: locationpocregistry.azurecr.io/producer-service:v1
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer
