name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: malarc/producer-service@v1.0

    - name: Set up Java
      uses: actions/setup-java@v1.0
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Tests
      run: mvn test
