name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: malarc/producer-service@main

#    - name: Set up Java
#      uses: malarc/producer-service@main
#      with:
#        distribution: 'adopt'
#        java-version: '11'
#
#    - name: Build with Maven
#      run: mvn -B clean install
#
#    - name: Run Tests
#      run: mvn test

#    - name: Set up node
#      uses: actions/setup-node@v1

    - name: Install dependencies
      run: mvn -B clean install

    - name: Run tests
      run: mvn test

#    - name: Build and test with Docker
#      run: docker build -t locationdatamaster .
