name: 'Build image'

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
      - 'master'

  push:
    branches:
      - 'main'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: producer-service
        uses: malarc/producer-service@v1.0
        with:
          percentage: 100
